import { WEEK_1_SEED } from "./seed-week1";

// Small helper so each game entry stays on one line and typos are easy to spot.
function g(id, day, time, away, home, network) {
  return {
    id, day, time, away, home, network,
    favorite: null, spread: null, awayScore: null, homeScore: null, final: false,
  };
}

// Pulled from CBS Sports' full 2026 season schedule. A handful of Week 16-18
// games are left out because the NFL hadn't announced those specific
// matchups yet (shown as "TBA vs TBA") -- add those with "Add a Game" once
// they're known, same as any other flex-scheduled game.
export const SEASON_SEED = {
  1: WEEK_1_SEED,

  2: [
    g("lions-bills-w2", "Thu 9/17", "8:15 PM ET", "Detroit Lions", "Buffalo Bills", "Amazon"),
    g("vikings-bears-w2", "Sun 9/20", "1:00 PM ET", "Minnesota Vikings", "Chicago Bears", "FOX"),
    g("eagles-titans-w2", "Sun 9/20", "1:00 PM ET", "Philadelphia Eagles", "Tennessee Titans", "FOX"),
    g("packers-jets-w2", "Sun 9/20", "1:00 PM ET", "Green Bay Packers", "New York Jets", "FOX"),
    g("panthers-falcons-w2", "Sun 9/20", "1:00 PM ET", "Carolina Panthers", "Atlanta Falcons", "FOX"),
    g("saints-ravens-w2", "Sun 9/20", "1:00 PM ET", "New Orleans Saints", "Baltimore Ravens", "CBS"),
    g("bengals-texans-w2", "Sun 9/20", "1:00 PM ET", "Cincinnati Bengals", "Houston Texans", "CBS"),
    g("browns-buccaneers-w2", "Sun 9/20", "1:00 PM ET", "Cleveland Browns", "Tampa Bay Buccaneers", "CBS"),
    g("steelers-patriots-w2", "Sun 9/20", "1:00 PM ET", "Pittsburgh Steelers", "New England Patriots", "CBS"),
    g("raiders-chargers-w2", "Sun 9/20", "4:05 PM ET", "Las Vegas Raiders", "Los Angeles Chargers", "CBS"),
    g("jaguars-broncos-w2", "Sun 9/20", "4:05 PM ET", "Jacksonville Jaguars", "Denver Broncos", "CBS"),
    g("commanders-cowboys-w2", "Sun 9/20", "4:25 PM ET", "Washington Commanders", "Dallas Cowboys", "FOX"),
    g("seahawks-cardinals-w2", "Sun 9/20", "4:25 PM ET", "Seattle Seahawks", "Arizona Cardinals", "FOX"),
    g("dolphins-49ers-w2", "Sun 9/20", "4:25 PM ET", "Miami Dolphins", "San Francisco 49ers", "FOX"),
    g("colts-chiefs-w2", "Sun 9/20", "8:20 PM ET", "Indianapolis Colts", "Kansas City Chiefs", "NBC"),
    g("giants-rams-w2", "Mon 9/21", "8:15 PM ET", "New York Giants", "Los Angeles Rams", "ESPN"),
  ],

  3: [
    g("falcons-packers-w3", "Thu 9/24", "8:15 PM ET", "Atlanta Falcons", "Green Bay Packers", "Amazon"),
    g("chiefs-dolphins-w3", "Sun 9/27", "1:00 PM ET", "Kansas City Chiefs", "Miami Dolphins", "CBS"),
    g("texans-colts-w3", "Sun 9/27", "1:00 PM ET", "Houston Texans", "Indianapolis Colts", "CBS"),
    g("titans-giants-w3", "Sun 9/27", "1:00 PM ET", "Tennessee Titans", "New York Giants", "CBS"),
    g("patriots-jaguars-w3", "Sun 9/27", "1:00 PM ET", "New England Patriots", "Jacksonville Jaguars", "CBS"),
    g("bengals-steelers-w3", "Sun 9/27", "1:00 PM ET", "Cincinnati Bengals", "Pittsburgh Steelers", "CBS"),
    g("panthers-browns-w3", "Sun 9/27", "1:00 PM ET", "Carolina Panthers", "Cleveland Browns", "FOX"),
    g("jets-lions-w3", "Sun 9/27", "1:00 PM ET", "New York Jets", "Detroit Lions", "FOX"),
    g("seahawks-commanders-w3", "Sun 9/27", "1:00 PM ET", "Seattle Seahawks", "Washington Commanders", "FOX"),
    g("chargers-bills-w3", "Sun 9/27", "1:00 PM ET", "Los Angeles Chargers", "Buffalo Bills", "FOX"),
    g("vikings-buccaneers-w3", "Sun 9/27", "4:05 PM ET", "Minnesota Vikings", "Tampa Bay Buccaneers", "FOX"),
    g("cardinals-49ers-w3", "Sun 9/27", "4:05 PM ET", "Arizona Cardinals", "San Francisco 49ers", "FOX"),
    g("ravens-cowboys-w3", "Sun 9/27", "4:25 PM ET", "Baltimore Ravens", "Dallas Cowboys", "CBS"),
    g("raiders-saints-w3", "Sun 9/27", "4:25 PM ET", "Las Vegas Raiders", "New Orleans Saints", "CBS"),
    g("rams-broncos-w3", "Sun 9/27", "8:20 PM ET", "Los Angeles Rams", "Denver Broncos", "NBC"),
    g("eagles-bears-w3", "Mon 9/28", "8:15 PM ET", "Philadelphia Eagles", "Chicago Bears", "ESPN"),
  ],

  4: [
    g("steelers-browns-w4", "Thu 10/1", "8:15 PM ET", "Pittsburgh Steelers", "Cleveland Browns", "Amazon"),
    g("colts-commanders-w4", "Sun 10/4", "9:30 AM ET", "Indianapolis Colts", "Washington Commanders", "NFL Network"),
    g("titans-ravens-w4", "Sun 10/4", "1:00 PM ET", "Tennessee Titans", "Baltimore Ravens", "CBS"),
    g("cardinals-giants-w4", "Sun 10/4", "1:00 PM ET", "Arizona Cardinals", "New York Giants", "CBS"),
    g("jaguars-bengals-w4", "Sun 10/4", "1:00 PM ET", "Jacksonville Jaguars", "Cincinnati Bengals", "CBS"),
    g("patriots-bills-w4", "Sun 10/4", "1:00 PM ET", "New England Patriots", "Buffalo Bills", "CBS"),
    g("cowboys-texans-w4", "Sun 10/4", "1:00 PM ET", "Dallas Cowboys", "Houston Texans", "FOX"),
    g("rams-eagles-w4", "Sun 10/4", "1:00 PM ET", "Los Angeles Rams", "Philadelphia Eagles", "FOX"),
    g("packers-buccaneers-w4", "Sun 10/4", "1:00 PM ET", "Green Bay Packers", "Tampa Bay Buccaneers", "FOX"),
    g("jets-bears-w4", "Sun 10/4", "1:00 PM ET", "New York Jets", "Chicago Bears", "FOX"),
    g("dolphins-vikings-w4", "Sun 10/4", "4:05 PM ET", "Miami Dolphins", "Minnesota Vikings", "FOX"),
    g("broncos-49ers-w4", "Sun 10/4", "4:25 PM ET", "Denver Broncos", "San Francisco 49ers", "CBS"),
    g("chargers-seahawks-w4", "Sun 10/4", "4:25 PM ET", "Los Angeles Chargers", "Seattle Seahawks", "CBS"),
    g("chiefs-raiders-w4", "Sun 10/4", "4:25 PM ET", "Kansas City Chiefs", "Las Vegas Raiders", "CBS"),
    g("lions-panthers-w4", "Sun 10/4", "8:20 PM ET", "Detroit Lions", "Carolina Panthers", "NBC"),
    g("falcons-saints-w4", "Mon 10/5", "8:15 PM ET", "Atlanta Falcons", "New Orleans Saints", "ESPN"),
  ],

  5: [
    g("buccaneers-cowboys-w5", "Thu 10/8", "8:15 PM ET", "Tampa Bay Buccaneers", "Dallas Cowboys", "Amazon"),
    g("eagles-jaguars-w5", "Sun 10/11", "9:30 AM ET", "Philadelphia Eagles", "Jacksonville Jaguars", "NFL Network"),
    g("raiders-patriots-w5", "Sun 10/11", "1:00 PM ET", "Las Vegas Raiders", "New England Patriots", "CBS"),
    g("texans-titans-w5", "Sun 10/11", "1:00 PM ET", "Houston Texans", "Tennessee Titans", "CBS"),
    g("browns-jets-w5", "Sun 10/11", "1:00 PM ET", "Cleveland Browns", "New York Jets", "CBS"),
    g("colts-steelers-w5", "Sun 10/11", "1:00 PM ET", "Indianapolis Colts", "Pittsburgh Steelers", "CBS"),
    g("bengals-dolphins-w5", "Sun 10/11", "1:00 PM ET", "Cincinnati Bengals", "Miami Dolphins", "FOX"),
    g("vikings-saints-w5", "Sun 10/11", "1:00 PM ET", "Minnesota Vikings", "New Orleans Saints", "FOX"),
    g("giants-commanders-w5", "Sun 10/11", "1:00 PM ET", "New York Giants", "Washington Commanders", "FOX"),
    g("broncos-chargers-w5", "Sun 10/11", "4:05 PM ET", "Denver Broncos", "Los Angeles Chargers", "CBS"),
    g("bears-packers-w5", "Sun 10/11", "4:25 PM ET", "Chicago Bears", "Green Bay Packers", "FOX"),
    g("lions-cardinals-w5", "Sun 10/11", "4:25 PM ET", "Detroit Lions", "Arizona Cardinals", "FOX"),
    g("49ers-seahawks-w5", "Sun 10/11", "4:25 PM ET", "San Francisco 49ers", "Seattle Seahawks", "FOX"),
    g("ravens-falcons-w5", "Sun 10/11", "8:20 PM ET", "Baltimore Ravens", "Atlanta Falcons", "NBC"),
    g("bills-rams-w5", "Mon 10/12", "8:15 PM ET", "Buffalo Bills", "Los Angeles Rams", "ESPN"),
  ],

  6: [
    g("seahawks-broncos-w6", "Thu 10/15", "8:15 PM ET", "Seattle Seahawks", "Denver Broncos", "Amazon"),
    g("texans-jaguars-w6", "Sun 10/18", "9:30 AM ET", "Houston Texans", "Jacksonville Jaguars", "NFL Network"),
    g("jets-patriots-w6", "Sun 10/18", "1:00 PM ET", "New York Jets", "New England Patriots", "CBS"),
    g("steelers-buccaneers-w6", "Sun 10/18", "1:00 PM ET", "Pittsburgh Steelers", "Tampa Bay Buccaneers", "CBS"),
    g("panthers-eagles-w6", "Sun 10/18", "1:00 PM ET", "Carolina Panthers", "Philadelphia Eagles", "CBS"),
    g("bears-falcons-w6", "Sun 10/18", "1:00 PM ET", "Chicago Bears", "Atlanta Falcons", "FOX"),
    g("titans-colts-w6", "Sun 10/18", "1:00 PM ET", "Tennessee Titans", "Indianapolis Colts", "FOX"),
    g("saints-giants-w6", "Sun 10/18", "1:00 PM ET", "New Orleans Saints", "New York Giants", "FOX"),
    g("ravens-browns-w6", "Sun 10/18", "1:00 PM ET", "Baltimore Ravens", "Cleveland Browns", "FOX"),
    g("cardinals-rams-w6", "Sun 10/18", "4:05 PM ET", "Arizona Cardinals", "Los Angeles Rams", "FOX"),
    g("chargers-chiefs-w6", "Sun 10/18", "4:25 PM ET", "Los Angeles Chargers", "Kansas City Chiefs", "CBS"),
    g("bills-raiders-w6", "Sun 10/18", "4:25 PM ET", "Buffalo Bills", "Las Vegas Raiders", "CBS"),
    g("cowboys-packers-w6", "Sun 10/18", "8:20 PM ET", "Dallas Cowboys", "Green Bay Packers", "NBC"),
    g("commanders-49ers-w6", "Mon 10/19", "8:15 PM ET", "Washington Commanders", "San Francisco 49ers", "ESPN"),
  ],

  7: [
    g("patriots-bears-w7", "Thu 10/22", "8:15 PM ET", "New England Patriots", "Chicago Bears", "Amazon"),
    g("steelers-saints-w7", "Sun 10/25", "9:30 AM ET", "Pittsburgh Steelers", "New Orleans Saints", "NFL Network"),
    g("browns-titans-w7", "Sun 10/25", "1:00 PM ET", "Cleveland Browns", "Tennessee Titans", "CBS"),
    g("dolphins-jets-w7", "Sun 10/25", "1:00 PM ET", "Miami Dolphins", "New York Jets", "CBS"),
    g("colts-vikings-w7", "Sun 10/25", "1:00 PM ET", "Indianapolis Colts", "Minnesota Vikings", "CBS"),
    g("bengals-ravens-w7", "Sun 10/25", "1:00 PM ET", "Cincinnati Bengals", "Baltimore Ravens", "CBS"),
    g("giants-texans-w7", "Sun 10/25", "1:00 PM ET", "New York Giants", "Houston Texans", "FOX"),
    g("buccaneers-panthers-w7", "Sun 10/25", "1:00 PM ET", "Tampa Bay Buccaneers", "Carolina Panthers", "FOX"),
    g("49ers-falcons-w7", "Sun 10/25", "1:00 PM ET", "San Francisco 49ers", "Atlanta Falcons", "FOX"),
    g("broncos-cardinals-w7", "Sun 10/25", "4:05 PM ET", "Denver Broncos", "Arizona Cardinals", "CBS"),
    g("rams-raiders-w7", "Sun 10/25", "4:25 PM ET", "Los Angeles Rams", "Las Vegas Raiders", "FOX"),
    g("packers-lions-w7", "Sun 10/25", "4:25 PM ET", "Green Bay Packers", "Detroit Lions", "FOX"),
    g("chiefs-seahawks-w7", "Sun 10/25", "8:20 PM ET", "Kansas City Chiefs", "Seattle Seahawks", "NBC"),
    g("cowboys-eagles-w7", "Mon 10/26", "8:15 PM ET", "Dallas Cowboys", "Philadelphia Eagles", "ESPN"),
  ],

  8: [
    g("panthers-packers-w8", "Thu 10/29", "8:15 PM ET", "Carolina Panthers", "Green Bay Packers", "Amazon"),
    g("titans-bengals-w8", "Sun 11/1", "1:00 PM ET", "Tennessee Titans", "Cincinnati Bengals", "CBS"),
    g("colts-jaguars-w8", "Sun 11/1", "1:00 PM ET", "Indianapolis Colts", "Jacksonville Jaguars", "CBS"),
    g("browns-steelers-w8", "Sun 11/1", "1:00 PM ET", "Cleveland Browns", "Pittsburgh Steelers", "CBS"),
    g("ravens-bills-w8", "Sun 11/1", "1:00 PM ET", "Baltimore Ravens", "Buffalo Bills", "CBS"),
    g("falcons-buccaneers-w8", "Sun 11/1", "1:00 PM ET", "Atlanta Falcons", "Tampa Bay Buccaneers", "FOX"),
    g("vikings-lions-w8", "Sun 11/1", "1:00 PM ET", "Minnesota Vikings", "Detroit Lions", "FOX"),
    g("cardinals-cowboys-w8", "Sun 11/1", "1:00 PM ET", "Arizona Cardinals", "Dallas Cowboys", "FOX"),
    g("raiders-jets-w8", "Sun 11/1", "1:00 PM ET", "Las Vegas Raiders", "New York Jets", "FOX"),
    g("chargers-rams-w8", "Sun 11/1", "4:05 PM ET", "Los Angeles Chargers", "Los Angeles Rams", "FOX"),
    g("chiefs-broncos-w8", "Sun 11/1", "4:25 PM ET", "Kansas City Chiefs", "Denver Broncos", "CBS"),
    g("patriots-dolphins-w8", "Sun 11/1", "4:25 PM ET", "New England Patriots", "Miami Dolphins", "CBS"),
    g("eagles-commanders-w8", "Sun 11/1", "8:20 PM ET", "Philadelphia Eagles", "Washington Commanders", "NBC"),
    g("bears-seahawks-w8", "Mon 11/2", "8:15 PM ET", "Chicago Bears", "Seattle Seahawks", "ESPN"),
  ],

  9: [
    g("jaguars-ravens-w9", "Thu 11/5", "8:15 PM ET", "Jacksonville Jaguars", "Baltimore Ravens", "Amazon"),
    g("bengals-falcons-w9", "Sun 11/8", "9:30 AM ET", "Cincinnati Bengals", "Atlanta Falcons", "NFL Network"),
    g("jets-chiefs-w9", "Sun 11/8", "1:00 PM ET", "New York Jets", "Kansas City Chiefs", "CBS"),
    g("browns-saints-w9", "Sun 11/8", "1:00 PM ET", "Cleveland Browns", "New Orleans Saints", "CBS"),
    g("broncos-panthers-w9", "Sun 11/8", "1:00 PM ET", "Denver Broncos", "Carolina Panthers", "CBS"),
    g("cowboys-colts-w9", "Sun 11/8", "1:00 PM ET", "Dallas Cowboys", "Indianapolis Colts", "FOX"),
    g("lions-dolphins-w9", "Sun 11/8", "1:00 PM ET", "Detroit Lions", "Miami Dolphins", "FOX"),
    g("giants-eagles-w9", "Sun 11/8", "1:00 PM ET", "New York Giants", "Philadelphia Eagles", "FOX"),
    g("rams-commanders-w9", "Sun 11/8", "1:00 PM ET", "Los Angeles Rams", "Washington Commanders", "FOX"),
    g("raiders-49ers-w9", "Sun 11/8", "4:05 PM ET", "Las Vegas Raiders", "San Francisco 49ers", "CBS"),
    g("texans-chargers-w9", "Sun 11/8", "4:05 PM ET", "Houston Texans", "Los Angeles Chargers", "CBS"),
    g("cardinals-seahawks-w9", "Sun 11/8", "4:25 PM ET", "Arizona Cardinals", "Seattle Seahawks", "FOX"),
    g("packers-patriots-w9", "Sun 11/8", "4:25 PM ET", "Green Bay Packers", "New England Patriots", "FOX"),
    g("buccaneers-bears-w9", "Sun 11/8", "8:20 PM ET", "Tampa Bay Buccaneers", "Chicago Bears", "NBC"),
    g("bills-vikings-w9", "Mon 11/9", "8:15 PM ET", "Buffalo Bills", "Minnesota Vikings", "ESPN"),
  ],

  10: [
    g("commanders-giants-w10", "Thu 11/12", "8:15 PM ET", "Washington Commanders", "New York Giants", "Amazon"),
    g("patriots-lions-w10", "Sun 11/15", "9:30 AM ET", "New England Patriots", "Detroit Lions", "FOX"),
    g("bills-jets-w10", "Sun 11/15", "1:00 PM ET", "Buffalo Bills", "New York Jets", "CBS"),
    g("dolphins-colts-w10", "Sun 11/15", "1:00 PM ET", "Miami Dolphins", "Indianapolis Colts", "CBS"),
    g("chiefs-falcons-w10", "Sun 11/15", "1:00 PM ET", "Kansas City Chiefs", "Atlanta Falcons", "CBS"),
    g("vikings-packers-w10", "Sun 11/15", "1:00 PM ET", "Minnesota Vikings", "Green Bay Packers", "FOX"),
    g("jaguars-titans-w10", "Sun 11/15", "1:00 PM ET", "Jacksonville Jaguars", "Tennessee Titans", "FOX"),
    g("texans-browns-w10", "Sun 11/15", "1:00 PM ET", "Houston Texans", "Cleveland Browns", "FOX"),
    g("panthers-saints-w10", "Sun 11/15", "1:00 PM ET", "Carolina Panthers", "New Orleans Saints", "FOX"),
    g("rams-cardinals-w10", "Sun 11/15", "4:05 PM ET", "Los Angeles Rams", "Arizona Cardinals", "CBS"),
    g("seahawks-raiders-w10", "Sun 11/15", "4:05 PM ET", "Seattle Seahawks", "Las Vegas Raiders", "CBS"),
    g("49ers-cowboys-w10", "Sun 11/15", "4:25 PM ET", "San Francisco 49ers", "Dallas Cowboys", "FOX"),
    g("steelers-bengals-w10", "Sun 11/15", "8:20 PM ET", "Pittsburgh Steelers", "Cincinnati Bengals", "NBC"),
    g("chargers-ravens-w10", "Mon 11/16", "8:15 PM ET", "Los Angeles Chargers", "Baltimore Ravens", "ESPN"),
  ],

  11: [
    g("colts-texans-w11", "Thu 11/19", "8:15 PM ET", "Indianapolis Colts", "Houston Texans", "Amazon"),
    g("cardinals-chiefs-w11", "Sun 11/22", "1:00 PM ET", "Arizona Cardinals", "Kansas City Chiefs", "CBS"),
    g("buccaneers-lions-w11", "Sun 11/22", "1:00 PM ET", "Tampa Bay Buccaneers", "Detroit Lions", "CBS"),
    g("jaguars-giants-w11", "Sun 11/22", "1:00 PM ET", "Jacksonville Jaguars", "New York Giants", "CBS"),
    g("dolphins-bills-w11", "Sun 11/22", "1:00 PM ET", "Miami Dolphins", "Buffalo Bills", "FOX"),
    g("titans-cowboys-w11", "Sun 11/22", "1:00 PM ET", "Tennessee Titans", "Dallas Cowboys", "FOX"),
    g("ravens-panthers-w11", "Sun 11/22", "1:00 PM ET", "Baltimore Ravens", "Carolina Panthers", "FOX"),
    g("saints-bears-w11", "Sun 11/22", "1:00 PM ET", "New Orleans Saints", "Chicago Bears", "FOX"),
    g("jets-chargers-w11", "Sun 11/22", "4:05 PM ET", "New York Jets", "Los Angeles Chargers", "FOX"),
    g("steelers-eagles-w11", "Sun 11/22", "4:25 PM ET", "Pittsburgh Steelers", "Philadelphia Eagles", "CBS"),
    g("raiders-broncos-w11", "Sun 11/22", "4:25 PM ET", "Las Vegas Raiders", "Denver Broncos", "CBS"),
    g("vikings-49ers-w11", "Sun 11/22", "8:20 PM ET", "Minnesota Vikings", "San Francisco 49ers", "NBC"),
    g("bengals-commanders-w11", "Mon 11/23", "8:15 PM ET", "Cincinnati Bengals", "Washington Commanders", "ESPN"),
  ],

  12: [
    g("packers-rams-w12", "Wed 11/25", "8:00 PM ET", "Green Bay Packers", "Los Angeles Rams", "Netflix"),
    g("bears-lions-w12", "Thu 11/26", "1:00 PM ET", "Chicago Bears", "Detroit Lions", "CBS"),
    g("eagles-cowboys-w12", "Thu 11/26", "4:30 PM ET", "Philadelphia Eagles", "Dallas Cowboys", "FOX"),
    g("chiefs-bills-w12", "Thu 11/26", "8:20 PM ET", "Kansas City Chiefs", "Buffalo Bills", "NBC"),
    g("broncos-steelers-w12", "Fri 11/27", "3:00 PM ET", "Denver Broncos", "Pittsburgh Steelers", "Amazon"),
    g("ravens-texans-w12", "Sun 11/29", "1:00 PM ET", "Baltimore Ravens", "Houston Texans", "CBS"),
    g("saints-bengals-w12", "Sun 11/29", "1:00 PM ET", "New Orleans Saints", "Cincinnati Bengals", "CBS"),
    g("jets-dolphins-w12", "Sun 11/29", "1:00 PM ET", "New York Jets", "Miami Dolphins", "CBS"),
    g("falcons-vikings-w12", "Sun 11/29", "1:00 PM ET", "Atlanta Falcons", "Minnesota Vikings", "FOX"),
    g("giants-colts-w12", "Sun 11/29", "1:00 PM ET", "New York Giants", "Indianapolis Colts", "FOX"),
    g("raiders-browns-w12", "Sun 11/29", "1:00 PM ET", "Las Vegas Raiders", "Cleveland Browns", "FOX"),
    g("titans-jaguars-w12", "Sun 11/29", "4:05 PM ET", "Tennessee Titans", "Jacksonville Jaguars", "CBS"),
    g("commanders-cardinals-w12", "Sun 11/29", "4:25 PM ET", "Washington Commanders", "Arizona Cardinals", "FOX"),
    g("seahawks-49ers-w12", "Sun 11/29", "4:25 PM ET", "Seattle Seahawks", "San Francisco 49ers", "FOX"),
    g("patriots-chargers-w12", "Sun 11/29", "8:20 PM ET", "New England Patriots", "Los Angeles Chargers", "NBC"),
    g("panthers-buccaneers-w12", "Mon 11/30", "8:15 PM ET", "Carolina Panthers", "Tampa Bay Buccaneers", "ESPN"),
  ],

  13: [
    g("chiefs-rams-w13", "Thu 12/3", "8:15 PM ET", "Kansas City Chiefs", "Los Angeles Rams", "Amazon"),
    g("lions-falcons-w13", "Sun 12/6", "1:00 PM ET", "Detroit Lions", "Atlanta Falcons", "CBS"),
    g("chargers-buccaneers-w13", "Sun 12/6", "1:00 PM ET", "Los Angeles Chargers", "Tampa Bay Buccaneers", "CBS"),
    g("commanders-titans-w13", "Sun 12/6", "1:00 PM ET", "Washington Commanders", "Tennessee Titans", "CBS"),
    g("bengals-browns-w13", "Sun 12/6", "1:00 PM ET", "Cincinnati Bengals", "Cleveland Browns", "CBS"),
    g("49ers-giants-w13", "Sun 12/6", "1:00 PM ET", "San Francisco 49ers", "New York Giants", "FOX"),
    g("packers-saints-w13", "Sun 12/6", "1:00 PM ET", "Green Bay Packers", "New Orleans Saints", "FOX"),
    g("jaguars-bears-w13", "Sun 12/6", "1:00 PM ET", "Jacksonville Jaguars", "Chicago Bears", "FOX"),
    g("eagles-cardinals-w13", "Sun 12/6", "4:05 PM ET", "Philadelphia Eagles", "Arizona Cardinals", "FOX"),
    g("dolphins-broncos-w13", "Sun 12/6", "4:05 PM ET", "Miami Dolphins", "Denver Broncos", "FOX"),
    g("panthers-vikings-w13", "Sun 12/6", "4:25 PM ET", "Carolina Panthers", "Minnesota Vikings", "CBS"),
    g("bills-patriots-w13", "Sun 12/6", "4:25 PM ET", "Buffalo Bills", "New England Patriots", "CBS"),
    g("texans-steelers-w13", "Sun 12/6", "8:20 PM ET", "Houston Texans", "Pittsburgh Steelers", "NBC"),
    g("cowboys-seahawks-w13", "Mon 12/7", "8:15 PM ET", "Dallas Cowboys", "Seattle Seahawks", "ESPN"),
  ],

  14: [
    g("vikings-patriots-w14", "Thu 12/10", "8:15 PM ET", "Minnesota Vikings", "New England Patriots", "Amazon"),
    g("broncos-jets-w14", "Sun 12/13", "1:00 PM ET", "Denver Broncos", "New York Jets", "CBS"),
    g("falcons-browns-w14", "Sun 12/13", "1:00 PM ET", "Atlanta Falcons", "Cleveland Browns", "CBS"),
    g("bears-dolphins-w14", "Sun 12/13", "1:00 PM ET", "Chicago Bears", "Miami Dolphins", "CBS"),
    g("texans-commanders-w14", "Sun 12/13", "1:00 PM ET", "Houston Texans", "Washington Commanders", "CBS"),
    g("saints-panthers-w14", "Sun 12/13", "1:00 PM ET", "New Orleans Saints", "Carolina Panthers", "CBS"),
    g("colts-eagles-w14", "Sun 12/13", "1:00 PM ET", "Indianapolis Colts", "Philadelphia Eagles", "FOX"),
    g("buccaneers-ravens-w14", "Sun 12/13", "1:00 PM ET", "Tampa Bay Buccaneers", "Baltimore Ravens", "FOX"),
    g("titans-lions-w14", "Sun 12/13", "1:00 PM ET", "Tennessee Titans", "Detroit Lions", "FOX"),
    g("chargers-raiders-w14", "Sun 12/13", "4:05 PM ET", "Los Angeles Chargers", "Las Vegas Raiders", "CBS"),
    g("chiefs-bengals-w14", "Sun 12/13", "4:25 PM ET", "Kansas City Chiefs", "Cincinnati Bengals", "FOX"),
    g("rams-49ers-w14", "Sun 12/13", "4:25 PM ET", "Los Angeles Rams", "San Francisco 49ers", "FOX"),
    g("giants-seahawks-w14", "Sun 12/13", "4:25 PM ET", "New York Giants", "Seattle Seahawks", "FOX"),
    g("bills-packers-w14", "Sun 12/13", "8:20 PM ET", "Buffalo Bills", "Green Bay Packers", "NBC"),
    g("steelers-jaguars-w14", "Mon 12/14", "8:15 PM ET", "Pittsburgh Steelers", "Jacksonville Jaguars", "ESPN"),
  ],

  15: [
    g("49ers-chargers-w15", "Thu 12/17", "8:15 PM ET", "San Francisco 49ers", "Los Angeles Chargers", "Amazon"),
    g("seahawks-eagles-w15", "Sat 12/19", "5:00 PM ET", "Seattle Seahawks", "Philadelphia Eagles", "FOX"),
    g("bears-bills-w15", "Sat 12/19", "8:20 PM ET", "Chicago Bears", "Buffalo Bills", "CBS"),
    g("jaguars-texans-w15", "Sun 12/20", "1:00 PM ET", "Jacksonville Jaguars", "Houston Texans", "CBS"),
    g("ravens-steelers-w15", "Sun 12/20", "1:00 PM ET", "Baltimore Ravens", "Pittsburgh Steelers", "CBS"),
    g("browns-giants-w15", "Sun 12/20", "1:00 PM ET", "Cleveland Browns", "New York Giants", "CBS"),
    g("colts-titans-w15", "Sun 12/20", "1:00 PM ET", "Indianapolis Colts", "Tennessee Titans", "CBS"),
    g("dolphins-packers-w15", "Sun 12/20", "1:00 PM ET", "Miami Dolphins", "Green Bay Packers", "FOX"),
    g("saints-buccaneers-w15", "Sun 12/20", "1:00 PM ET", "New Orleans Saints", "Tampa Bay Buccaneers", "FOX"),
    g("bengals-panthers-w15", "Sun 12/20", "1:00 PM ET", "Cincinnati Bengals", "Carolina Panthers", "FOX"),
    g("falcons-commanders-w15", "Sun 12/20", "1:00 PM ET", "Atlanta Falcons", "Washington Commanders", "FOX"),
    g("jets-cardinals-w15", "Sun 12/20", "4:05 PM ET", "New York Jets", "Arizona Cardinals", "FOX"),
    g("cowboys-rams-w15", "Sun 12/20", "4:25 PM ET", "Dallas Cowboys", "Los Angeles Rams", "CBS"),
    g("broncos-raiders-w15", "Sun 12/20", "4:25 PM ET", "Denver Broncos", "Las Vegas Raiders", "CBS"),
    g("lions-vikings-w15", "Sun 12/20", "8:20 PM ET", "Detroit Lions", "Minnesota Vikings", "NBC"),
    g("patriots-chiefs-w15", "Mon 12/21", "8:15 PM ET", "New England Patriots", "Kansas City Chiefs", "ESPN"),
  ],

  16: [
    g("texans-eagles-w16", "Thu 12/24", "8:15 PM ET", "Houston Texans", "Philadelphia Eagles", "Amazon"),
    g("packers-bears-w16", "Fri 12/25", "1:00 PM ET", "Green Bay Packers", "Chicago Bears", "Netflix"),
    g("bills-broncos-w16", "Fri 12/25", "4:30 PM ET", "Buffalo Bills", "Denver Broncos", "Netflix"),
    g("rams-seahawks-w16", "Fri 12/25", "8:15 PM ET", "Los Angeles Rams", "Seattle Seahawks", "FOX"),
    g("buccaneers-falcons-w16", "Sun 12/27", "TBD", "Tampa Bay Buccaneers", "Atlanta Falcons", "TBD"),
    g("commanders-vikings-w16", "Sun 12/27", "TBD", "Washington Commanders", "Minnesota Vikings", "TBD"),
    g("panthers-steelers-w16", "Sun 12/27", "TBD", "Carolina Panthers", "Pittsburgh Steelers", "TBD"),
    g("bengals-colts-w16", "Sun 12/27", "TBD", "Cincinnati Bengals", "Indianapolis Colts", "TBD"),
    g("patriots-jets-w16", "Sun 12/27", "1:00 PM ET", "New England Patriots", "New York Jets", "CBS"),
    g("browns-ravens-w16", "Sun 12/27", "1:00 PM ET", "Cleveland Browns", "Baltimore Ravens", "CBS"),
    g("chargers-dolphins-w16", "Sun 12/27", "1:00 PM ET", "Los Angeles Chargers", "Miami Dolphins", "FOX"),
    g("cardinals-raiders-w16", "Sun 12/27", "4:05 PM ET", "Arizona Cardinals", "Las Vegas Raiders", "FOX"),
    g("49ers-chiefs-w16", "Sun 12/27", "4:25 PM ET", "San Francisco 49ers", "Kansas City Chiefs", "CBS"),
    g("jaguars-cowboys-w16", "Sun 12/27", "8:20 PM ET", "Jacksonville Jaguars", "Dallas Cowboys", "NBC"),
    g("giants-lions-w16", "Mon 12/28", "8:15 PM ET", "New York Giants", "Detroit Lions", "ESPN"),
  ],

  17: [
    g("ravens-bengals-w17", "Thu 12/31", "8:15 PM ET", "Baltimore Ravens", "Cincinnati Bengals", "Amazon"),
    g("rams-buccaneers-w17", "Sun 1/3", "TBD", "Los Angeles Rams", "Tampa Bay Buccaneers", "TBD"),
    g("broncos-patriots-w17", "Sun 1/3", "TBD", "Denver Broncos", "New England Patriots", "TBD"),
    g("chiefs-chargers-w17", "Sun 1/3", "TBD", "Kansas City Chiefs", "Los Angeles Chargers", "TBD"),
    g("commanders-jaguars-w17", "Sun 1/3", "TBD", "Washington Commanders", "Jacksonville Jaguars", "TBD"),
    g("bills-dolphins-w17", "Sun 1/3", "1:00 PM ET", "Buffalo Bills", "Miami Dolphins", "CBS"),
    g("steelers-titans-w17", "Sun 1/3", "1:00 PM ET", "Pittsburgh Steelers", "Tennessee Titans", "CBS"),
    g("vikings-jets-w17", "Sun 1/3", "1:00 PM ET", "Minnesota Vikings", "New York Jets", "CBS"),
    g("saints-falcons-w17", "Sun 1/3", "1:00 PM ET", "New Orleans Saints", "Atlanta Falcons", "FOX"),
    g("seahawks-panthers-w17", "Sun 1/3", "1:00 PM ET", "Seattle Seahawks", "Carolina Panthers", "FOX"),
    g("colts-browns-w17", "Sun 1/3", "1:00 PM ET", "Indianapolis Colts", "Cleveland Browns", "FOX"),
    g("giants-cowboys-w17", "Sun 1/3", "1:00 PM ET", "New York Giants", "Dallas Cowboys", "FOX"),
    g("raiders-cardinals-w17", "Sun 1/3", "4:05 PM ET", "Las Vegas Raiders", "Arizona Cardinals", "CBS"),
    g("lions-bears-w17", "Sun 1/3", "4:25 PM ET", "Detroit Lions", "Chicago Bears", "FOX"),
    g("eagles-49ers-w17", "Sun 1/3", "8:20 PM ET", "Philadelphia Eagles", "San Francisco 49ers", "NBC"),
    g("texans-packers-w17", "Mon 1/4", "8:15 PM ET", "Houston Texans", "Green Bay Packers", "ESPN"),
  ],

  18: [
    g("jets-bills-w18", "Sun 1/10", "TBD", "New York Jets", "Buffalo Bills", "TBD"),
    g("jaguars-colts-w18", "Sun 1/10", "TBD", "Jacksonville Jaguars", "Indianapolis Colts", "TBD"),
    g("raiders-chiefs-w18", "Sun 1/10", "TBD", "Las Vegas Raiders", "Kansas City Chiefs", "TBD"),
    g("titans-texans-w18", "Sun 1/10", "TBD", "Tennessee Titans", "Houston Texans", "TBD"),
    g("chargers-broncos-w18", "Sun 1/10", "TBD", "Los Angeles Chargers", "Denver Broncos", "TBD"),
    g("dolphins-patriots-w18", "Sun 1/10", "TBD", "Miami Dolphins", "New England Patriots", "TBD"),
    g("browns-bengals-w18", "Sun 1/10", "TBD", "Cleveland Browns", "Cincinnati Bengals", "TBD"),
    g("steelers-ravens-w18", "Sun 1/10", "TBD", "Pittsburgh Steelers", "Baltimore Ravens", "TBD"),
    g("bears-vikings-w18", "Sun 1/10", "TBD", "Chicago Bears", "Minnesota Vikings", "TBD"),
    g("lions-packers-w18", "Sun 1/10", "TBD", "Detroit Lions", "Green Bay Packers", "TBD"),
    g("cowboys-commanders-w18", "Sun 1/10", "TBD", "Dallas Cowboys", "Washington Commanders", "TBD"),
    g("buccaneers-saints-w18", "Sun 1/10", "TBD", "Tampa Bay Buccaneers", "New Orleans Saints", "TBD"),
    g("eagles-giants-w18", "Sun 1/10", "TBD", "Philadelphia Eagles", "New York Giants", "TBD"),
    g("seahawks-rams-w18", "Sun 1/10", "TBD", "Seattle Seahawks", "Los Angeles Rams", "TBD"),
    g("falcons-panthers-w18", "Sun 1/10", "TBD", "Atlanta Falcons", "Carolina Panthers", "TBD"),
    g("49ers-cardinals-w18", "Sun 1/10", "TBD", "San Francisco 49ers", "Arizona Cardinals", "TBD"),
  ],
};
