export const WEEK_1_SEED = [
  { id: "ne-sea", day: "Wed 9/9", time: "8:20 PM ET", away: "New England", home: "Seattle", network: "NBC", favorite: null, spread: null },
  { id: "sf-lar", day: "Thu 9/10", time: "8:35 PM ET", away: "San Francisco", home: "LA Rams", network: "Netflix", favorite: null, spread: null },
  { id: "atl-pit", day: "Sun 9/13", time: "1:00 PM ET", away: "Atlanta", home: "Pittsburgh", network: "FOX", favorite: null, spread: null },
  { id: "bal-ind", day: "Sun 9/13", time: "1:00 PM ET", away: "Baltimore", home: "Indianapolis", network: "CBS", favorite: null, spread: null },
  { id: "buf-hou", day: "Sun 9/13", time: "1:00 PM ET", away: "Buffalo", home: "Houston", network: "CBS", favorite: null, spread: null },
  { id: "chi-car", day: "Sun 9/13", time: "1:00 PM ET", away: "Chicago", home: "Carolina", network: "FOX", favorite: null, spread: null },
  { id: "cle-jac", day: "Sun 9/13", time: "1:00 PM ET", away: "Cleveland", home: "Jacksonville", network: "CBS", favorite: null, spread: null },
  { id: "no-det", day: "Sun 9/13", time: "1:00 PM ET", away: "New Orleans", home: "Detroit", network: "FOX", favorite: null, spread: null },
  { id: "nyj-ten", day: "Sun 9/13", time: "1:00 PM ET", away: "NY Jets", home: "Tennessee", network: "CBS", favorite: null, spread: null },
  { id: "tb-cin", day: "Sun 9/13", time: "1:00 PM ET", away: "Tampa Bay", home: "Cincinnati", network: "FOX", favorite: null, spread: null },
  { id: "ari-lac", day: "Sun 9/13", time: "4:25 PM ET", away: "Arizona", home: "LA Chargers", network: "CBS", favorite: null, spread: null },
  { id: "gb-min", day: "Sun 9/13", time: "4:25 PM ET", away: "Green Bay", home: "Minnesota", network: "CBS", favorite: null, spread: null },
  { id: "mia-lv", day: "Sun 9/13", time: "4:25 PM ET", away: "Miami", home: "Las Vegas", network: "FOX", favorite: null, spread: null },
  { id: "was-phi", day: "Sun 9/13", time: "4:25 PM ET", away: "Washington", home: "Philadelphia", network: "FOX", favorite: null, spread: null },
  { id: "dal-nyg", day: "Sun 9/13", time: "8:20 PM ET", away: "Dallas", home: "NY Giants", network: "NBC", favorite: null, spread: null },
  { id: "den-kc", day: "Mon 9/14", time: "8:15 PM ET", away: "Denver", home: "Kansas City", network: "ABC", favorite: null, spread: null },
];
